# Generated by Django 5.1.7 on 2025-03-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='rol',
            field=models.CharField(default='Estudiante', max_length=20),
        ),
    ]
