# Generated by Django 5.1.7 on 2025-03-26 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasaporte', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/pasaporte/')),
                ('documento_identidad', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/identidad/')),
                ('antecedentes_penales', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/antecedentes/')),
                ('seguro_medico', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/seguro/')),
                ('carta_inscripcion', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/carta_inscripcion/')),
                ('recibo_pago', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/pago/')),
                ('diploma_traducido', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/diploma/')),
                ('transcripcion_traducida', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/transcripcion/')),
                ('carta_intencion', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/carta_intencion/')),
                ('resumen_financiero', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/resumen_financiero/')),
                ('extracto_bancario', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/extracto_bancario/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='estudiantes.estudiantes')),
            ],
        ),
    ]
