# Generated by Django 5.1.7 on 2025-03-26 04:35

import estudiantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_documentosestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosestudiante',
            name='codigo_inscripcion',
            field=models.CharField(blank=True, editable=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='antecedentes_penales',
            field=models.FileField(default=1, upload_to='documentos_estudiantes/antecedentes/', validators=[estudiantes.models.validar_archivo]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='carta_inscripcion',
            field=models.FileField(default=1, upload_to='documentos_estudiantes/carta_inscripcion/', validators=[estudiantes.models.validar_archivo]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='carta_intencion',
            field=models.FileField(default=1, upload_to='documentos_estudiantes/carta_intencion/', validators=[estudiantes.models.validar_archivo]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='diploma_traducido',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/diploma/', validators=[estudiantes.models.validar_archivo]),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='documento_identidad',
            field=models.FileField(default=1, upload_to='documentos_estudiantes/identidad/', validators=[estudiantes.models.validar_archivo]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='extracto_bancario',
            field=models.FileField(default=1, upload_to='documentos_estudiantes/extracto_bancario/', validators=[estudiantes.models.validar_archivo]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='pasaporte',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/pasaporte/', validators=[estudiantes.models.validar_archivo]),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='recibo_pago',
            field=models.FileField(default=1, upload_to='documentos_estudiantes/pago/', validators=[estudiantes.models.validar_archivo]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='resumen_financiero',
            field=models.FileField(default=1, upload_to='documentos_estudiantes/resumen_financiero/', validators=[estudiantes.models.validar_archivo]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='seguro_medico',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/seguro/', validators=[estudiantes.models.validar_archivo]),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='transcripcion_traducida',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/transcripcion/', validators=[estudiantes.models.validar_archivo]),
        ),
    ]
