# Generated by Django 5.1.7 on 2025-03-26 19:02

import estudiantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_documentosestudiante_codigo_inscripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosestudiante',
            name='estado_inscripcion',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='antecedentes_penales',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/antecedentes/', validators=[estudiantes.models.validar_archivo]),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='carta_inscripcion',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/carta_inscripcion/', validators=[estudiantes.models.validar_archivo]),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='carta_intencion',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/carta_intencion/', validators=[estudiantes.models.validar_archivo]),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='documento_identidad',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/identidad/', validators=[estudiantes.models.validar_archivo]),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='extracto_bancario',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/extracto_bancario/', validators=[estudiantes.models.validar_archivo]),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='recibo_pago',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/pago/', validators=[estudiantes.models.validar_archivo]),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='resumen_financiero',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/resumen_financiero/', validators=[estudiantes.models.validar_archivo]),
        ),
    ]
